Translate introduce-your-team-to-KMM
2BAB/kotlin-mobile-docs pull request #11
Opened 2021-06-29 03:29 UTC by Jasmine-liang

- [X] 已仔细阅读中文站 repo [issue⁠35](https://github.com/hltj/kotlin-web-site-cn/issues/35) 及其中链接的内容
- [X] 阅读过 Kotlin 参考的大部分章节
- [X] 每一句都已经过谷歌机翻作为参考
- [X] 每一句都已经过搜狗机翻作为参考
- [X] 翻译中所用术语均与术语表中一致
- [X] 注释也已翻译，除了 `//sampleStart` 与 `//sampleEnd`，`[//]: # (title: Xxxx) [//]: # (auxiliary-id: Xxxx)`
- [X] 正文与注释中的标点均已使用全角
- [X] 中文与英文/数字之间、中文与 `` ` `` 之间都以空格分隔
- [X] 英文与标点之间未留空格

2021-07-12 08:13 UTC, 2BAB requested changes

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +*   **[Chalk.com](https://kotlinlang.org/lp/mobile/case-studies/chalk)** – 该网站的每个应用的 UI 都是原生的，但除此之外，他们的应用的几乎所有东西都可以与 Kotlin 移动多平台（KMM）共享。
Chalk.com 上的每个应用

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +*   **[Chalk.com](https://kotlinlang.org/lp/mobile/case-studies/chalk)** – 该网站的每个应用的 UI 都是原生的，但除此之外，他们的应用的几乎所有东西都可以与 Kotlin 移动多平台（KMM）共享。
都可以藉由 Kotlin 移动多平台（KMM）进行共享。

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +探索 [案例研究页面](https://kotlinlang.org/lp/mobile/case-studies) ，了解鼓舞人心的相关参考资料。
我觉得“启发灵感的”，比“鼓舞人心的”在此处更合适一些。

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +探索 [案例研究页面](https://kotlinlang.org/lp/mobile/case-studies) ，了解鼓舞人心的相关参考资料。
访问[案例研究](...)，了解更多启发灵感的相关资料。

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +学习理论是不错的，但最终将其付诸实践才是最重要的。为了使案例更有说服力，你可以冒险花一些个人空闲时间，用 KMM 捣鼓一些东西，然后把结果拿出来让团队讨论。原型可以是某种测试项目，从头开始编写，并展示应用中需要的功能。[网络和数据存储实战教程](https://play.kotlinlang.org/hands-on/Networking%20and%20data%20storage%20wit
理论的学习有其好处，

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +答：实际上没有必要。有多种可以构建 KMM 应用的方法来组织工作流程。首先，只有 Android 开发人员可以负责构建，在这种情况下，iOS 团队将只编写代码，甚至只消费生成的构件。可以在面对需要与 Gradle 一起工作的任务时组织一些工作坊或练习结对编程，这将提高团队的 Gradle 技能。你还可以探索不同的[多平台项目团队合作组织方式](organize-process-around-km
workshop -> 研讨会
“的方式”可以不用。

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +当只有团队中的 Android 部分使用共享代码工作时，iOS 开发者甚至不需要学习 Kotlin。但是当准备好让团队进入下一个阶段，每个人都为共享代码做出贡献时，进行过渡就不会花太多时间。Swift 和 Kotlin 的语法和功能的相似性大大减少了学习如何阅读和编写共享 Kotlin 代码所需的工作。[自己试试吧！](https://play.kotlinlang.org/koans/over
Swift 和 Kotlin 语法和功能的相似性极大减少了
（这样感觉读起来比较通顺

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +现在也是在 KMM 开源社区做 iOS 开发者的好时机，因为社区对开发 iOS 的经验很有需求，而且有很多机会可以从对 iOS 的具体贡献中获得认可。
因为 KMM 也需要 iOS 开发经验，而且有大量的机会让你从 iOS 端的贡献中获得认可。

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +在决定使用 KMM 之后，团队将会有一段适应期来试验这项技术。但你的任务还没有结束！通过为队友提供持续的支持，将减少团队投入技术并取得初步成果所需的时间。
将缩短团队深入技术细节、取得初步成功所需的时间

2021-07-12 08:13 UTC, 2BAB commented on topics-zh-CN/introduce-your-team-to-kmm.md
> +* 组织一次非正式的团队建设活动，吃爆米花和披萨，观看关于 KMM 的教育或励志视频。Ben Asher 和 Alec Strong 的[在 iOS 和 Android 上发布多平台移动项目](https://www.youtube.com/watch?v=je8aqW48JiA) 可能是一个不错的选择。
观看关于 KMM 的分享或启发性视频

2021-07-29 01:35 UTC, 2BAB commented
诶，第二次的 commit 只改了一处，其他9处你直接 resolved without commits，方便写下原因吗，讨论下~

2021-07-29 03:11 UTC, Jasmine-liang commented
> 诶，第二次的 commit 只改了一处，其他9处你直接 resolved without commits，方便写下原因吗，讨论下~

其他9处我也改啦~ 第一次commit的时候发现还有一处没改orz, 又不想commit 两次 "Update ..."， 于是就git --reset hard回退了, 也就回到了已经修改了9处的状态:)

2021-08-07 12:25 UTC, merged