finish add-dependecies translate and remain two issues
2BAB/kotlin-mobile-docs pull request #2
Opened 2021-03-23 12:53 UTC by messi-wpy

完成 add-dependecies.md 的翻译，但有两个问题有待解决

1. 有一句不懂咋翻译，不知道 `out of box`具体是啥意思：（文中有这两处用到）
- This issue doesn't apply to platform libraries supported out of the box.
- Third-party iOS libraries, with the exception of platform libraries supported out of the box.

2.一个md格式的锚点无法正常点击
[这个解决方案](#为共享的-ios-源集启用-ide-支持的解决方法)  这个锚点不能正常链接到文章中的位置，发现原版英文文档里也有这个问题，原因是
文件里的标题是：
### 为共享的 iOS 源集启用 IDE 支持的解决方法 {initial-collapse-state="collapsed"}
后面多了 {initial-collapse-state="collapsed"}，用与之后在网站上显示折叠状态

2021-03-24 14:34 UTC, 2BAB commented
> supported out of the box 
是开箱即用的意思，比如第一句，就是这个问题并不适用于某些开箱即用的平台库（结合上下文就是它们可以支持 IDE 高亮补全之类的特性吧）。

第二个问题就先留着吧，原文怎么写的格式，咱就保持好了。

2021-03-24 14:35 UTC, 2BAB commented
具体中英翻译对比还没看完，占个坑明儿搞完它。

2021-03-27 02:45 UTC, 2BAB requested changes

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +每个应用程序都需要一组函数库才能运行成功。
都需要一些库才能良好运转。

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +从这里学习如何添加：
在这里你可以学到如何添加：

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +--> [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) 与 [SQLDelight](https://github.com/cashapp/sqldelight) 。
这个 `<!---->` 是？

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对Kotlin 标准库](#对-kotlin-标准库的依赖项)
中英文间加空格

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对Kotlin 标准库](#对-kotlin-标准库的依赖项)
对 -> 针对，下面几个同理

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对所有源集共享的库](#对所有源集共享的库的依赖项)
针对所有 source sets 的库

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对指定源集中使用的库](#对指定源集中使用的库的依赖项)
针对指定 source sets 的库，

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对指定源集中使用的库](#对指定源集中使用的库的依赖项)
source sets 基本上用 gradle 的都知道，应该不用翻译，这里翻译了很难理解我觉得。后面用到的地方自己改一下~

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +* [对另一个多平台项目](#对另一个多平台项目的依赖项)
针对

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +### 对 Kotlin 标准库的依赖项
针对，后面的也一样，就不写了

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +如果想从任一个源集中使用库，那么可以只将其添加到公共源集中。
可以只 -> 只可以

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +Apple SDK 依赖项（例如 Foundation 或 Core Bluetooth）作为 Kotlin Multiplatform Mobile 项目中的一组预构建库提供。
KMM 需要翻译，因为其他地方都翻了，包括目录

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +与 CocoaPods 依赖项管理器的集成也受到同样的限制——不能使用纯 Swift pod。
去掉 与，中文有些 with 的用法不一定需要翻译

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +Apple SDK 依赖项（例如 Foundation 或 Core Bluetooth）作为 Kotlin Multiplatform Mobile 项目中的一组预构建库提供。
可以采用 ”Kotlin 移动多平台（KMM）项目“ 这个写法，兼顾了中翻和英文简写快速理解

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +仅当您想要专门参与交互操作调优过程或有其他强有力的理由这样做时,再去[手动管理依赖关系](#不使用-CocoaPods)。
再去 -> 才使用[手动...]，仅...才.. 感觉比较通畅

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +仅当您想要专门参与交互操作调优过程或有其他强有力的理由这样做时,再去[手动管理依赖关系](#不使用-CocoaPods)。
仅当你明确地想调整（两门语言）互操作的过程

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +1. 执行 [初始 CocoaPods 集成设置](https://kotlinlang.org/docs/reference/native/cocoapods.html#install-the-cocoapods-dependency-manager-and-plugin)
初始化

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +2. 通过编写项目构建脚本中的 `pod()`，添加要使用的 CocoaPods 版本库中的Pod库依赖项。
中英文空格分隔

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +如需在 Kotlin 代码中使用该依赖项，可导入软件包 `cocoapods.<library-name>`。在上面的示例中，那将是：
that would be: -> 即：

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +了解更多关于[CocoaPods 集成](https://kotlinlang.org/docs/reference/native/cocoapods.html)。
中英文之间加空格

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +如果不想使用 CocoaPods，那么可以使用 cinterop 工具为 Objective 或 Swift 声明创建 Kotlin 绑定。这样就可以通过 Kotlin 代码去调用它们。为此：
的声明创建，不然声明看起来和动词一样

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +2. 构建它并获取它的二进制文件。
构建它 -> 构建

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +[代码库](#不使用-cocoapods-添加库)和[框架](#不使用-cocoapods-添加一个框架)的步骤有所不同，但是它们的思想是一样的。
library 翻译成库应该还行，但是 framework 我觉得不用翻译。这是一种 iOS/macOS 开发中的特有格式，跟 Android .aar 有点类似，https://medium.com/@zippicoder/libraries-frameworks-swift-packages-whats-the-difference-764f371444cd

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +现在即可以在你的 Kotlin 代码中使用这个依赖项。为此，导入之前在 `.def` 文件里设置的 `package` 属性。在上面的示例中，这将是：
现在你可以在你的 Kotlin 代码中使用该依赖项，即导入那个之前在 `.def` 文件里的 `package` 配置对应的包。

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +现在即可以在你的 Kotlin 代码中使用这个依赖项。为此，导入之前在 `.def` 文件里设置的 `package` 属性。在上面的示例中，这将是：
参考上个改法

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +在此代码示例中，iOS 目标平台的配置取决于 `SDK_NAME` 这个环境变量，该变量由 Xcode 管理。
去掉 这个

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +> 这是一个临时的解决方法。如果你是一个软件库作者，我们推荐尽快[迁移到层次结构](https://kotlinlang.org/docs/migrating-multiplatform-project-to-14.html#migrate-to-the-hierarchical-project-structure)。
分层项目结构 https://www.kotlincn.net/docs/reference/migrating-multiplatform-project-to-14.html 我看主站的翻译是这样，你要不要参考下把用到的地方都改了。

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +> 这是一个[已知问题](https://youtrack.jetbrains.com/issue/KT-40975)，我们正在努力解决它。与此同时，你可以使用[这个解决方案](#为共享的-ios-源集启用-ide-支持的解决方法)。
workaround -> 变通方案，其他地方的自己改下哈

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +> 通过这种解决方法，Kotlin 多平台工具仅针对当前构建期间处于活动状态的一个原生目标平台来分析您的代码。
workaround -> 变通方案

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +建议通过将 Android 依赖项添加到具体的 Android 源集中来将其添加到 KMM 项目中。
我们建议通过”将 Android 依赖项添加到具体的 Android source set 中“来将其集成到 KMM 项目中。

（原文就有点尴尬，这里我稍微意译了一两个词，不然读起来很不通车）

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +如果一个 Android 项目中的顶层依赖项有一个特殊的配置名称，那么将这个项目中的一个顶层依赖项移动到 KMM 项目中的指定源集里可能会很困难。例如，要在Android项目的顶层移动一个 `debugImplementation` 依赖项，需要向名为 `androidDebug` 的源集添加实现依赖项。
中英文之间加空格

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +还支持以 Android 项目惯用的方式，将依赖项放入脚本末尾的独立 `dependencies` 块中。但是，我们强烈**反对**这样做，因为在构建脚本的顶层代码块中配置一个 Android 依赖项而在每个源集中配置其他目标平台依赖项，将很可能会导致混乱。
很可能会引发混淆。

2021-03-27 02:45 UTC, 2BAB commented on topics-zh-CN/add-dependencies.md
> +到 Android 官方文档了解更多关于[添加依赖项](https://developer.android.com/studio/build/dependencies)的信息。
前往 Android 官方文档

2021-03-27 02:47 UTC, 2BAB commented
记得把 PR checklist 的东西补上，可以参考我的第一个 PR

2021-03-27 04:41 UTC, messi-wpy reviewed
好的好的，我下午改一下，下次一定注意中英文空格问题，

2021-03-27 04:41 UTC, messi-wpy commented on topics-zh-CN/add-dependencies.md
> +--> [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) 与 [SQLDelight](https://github.com/cashapp/sqldelight) 。
这个是规范里面要求得行级对照呀，在非标点断句处添加html注释标记

2021-03-27 04:41 UTC, messi-wpy commented on topics-zh-CN/add-dependencies.md
> +如果想从任一个源集中使用库，那么可以只将其添加到公共源集中。
这里改成 只可以 意思是不是变了呀，我其实也能不这样做呀

2021-03-30 03:20 UTC, messi-wpy commented
- [x] 已仔细阅读中文站 repo [issue⁠35](https://github.com/hltj/kotlin-web-site-cn/issues/35) 及其中链接的内容
- [x] 阅读过 Kotlin 参考的大部分章节
- [x] 每一句都已经过谷歌机翻作为参考
- [x] 每一句都已经过搜狗机翻作为参考
- [x] 翻译中所用术语均与术语表中一致
- [x] 注释也已翻译，除了 `//sampleStart` 与 `//sampleEnd`，`[//]: # (title: Xxxx)
[//]: # (auxiliary-id: Xxxx)`
- [x] 正文与注释中的标点均已使用全角
- [x] 中文与英文/数字之间、中文与 `` ` `` 之间都以空格分隔
- [x] 英文与标点之间未留空格
- [x] 行级对照，中文句子中间断行处已使用 HTML 注释

2021-03-31 14:15 UTC, 2BAB approved these changes

2021-03-31 14:15 UTC, merged